/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package Jflextest;
import static Jflextest.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>NewLexer.flex</tt>
 */
class NewLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\17\1\20\1\20\1\17\22\0\1\17\7\0\1\5"+
    "\1\6\3\0\1\7\1\12\1\0\1\2\1\15\1\15\1\15\1\16"+
    "\1\14\1\15\3\2\6\0\1\13\32\1\1\10\1\0\1\11\1\0"+
    "\1\4\1\0\32\3\12\0\1\20\u1fa2\0\1\20\1\20\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\10\1\1\2\13\0\1\3\24\0\1\4\6\0"+
    "\2\4\5\0\1\4\20\0\1\5\16\0\1\6\7\0"+
    "\1\5\1\7\1\10";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\21\0\42\0\63\0\104\0\125\0\146\0\167"+
    "\0\210\0\231\0\42\0\104\0\252\0\273\0\314\0\335"+
    "\0\356\0\377\0\u0110\0\u0121\0\u0132\0\u0143\0\u0154\0\u0165"+
    "\0\u0176\0\u0187\0\u0198\0\u01a9\0\u01ba\0\u01cb\0\u01dc\0\u01ed"+
    "\0\u01fe\0\u020f\0\u0220\0\u0231\0\u0242\0\u0253\0\u0264\0\u0275"+
    "\0\u0286\0\u0297\0\u02a8\0\u02b9\0\u02ca\0\u02db\0\u02ec\0\u02fd"+
    "\0\u030e\0\u031f\0\u0330\0\u0341\0\u0352\0\u0363\0\u0374\0\u0385"+
    "\0\u0396\0\u03a7\0\u03b8\0\u03c9\0\u03da\0\u03eb\0\u03fc\0\u040d"+
    "\0\u041e\0\u042f\0\u0440\0\u0451\0\u0462\0\u0473\0\u0484\0\u0495"+
    "\0\u04a6\0\u04b7\0\u04c8\0\u04d9\0\u04ea\0\u04fb\0\u050c\0\u051d"+
    "\0\u052e\0\u053f\0\u0550\0\u0561\0\u0572\0\u0583\0\u0594\0\u05a5"+
    "\0\21\0\u05b6\0\u05c7\0\u05d8\0\u04b7\0\u05e9\0\u05fa\0\u060b"+
    "\0\21\0\21\0\21";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\2\2\1\7"+
    "\3\2\1\10\1\4\1\11\1\12\23\0\1\13\1\14"+
    "\1\15\1\16\2\0\1\14\2\0\1\14\1\17\3\14"+
    "\4\0\1\20\11\0\3\20\3\0\4\14\2\0\1\14"+
    "\2\0\1\14\1\17\3\14\4\0\1\21\11\0\3\21"+
    "\4\0\1\22\11\0\3\22\4\0\1\20\11\0\3\23"+
    "\4\0\1\24\11\0\3\24\21\0\1\12\2\0\2\14"+
    "\1\15\1\16\2\0\1\14\2\0\1\14\1\17\3\14"+
    "\3\0\1\25\2\14\1\16\2\0\1\14\2\0\1\14"+
    "\1\17\3\14\3\0\1\26\1\0\1\26\7\0\1\17"+
    "\7\0\1\27\4\0\1\30\4\0\3\27\4\0\1\31"+
    "\11\0\3\31\4\0\1\32\11\0\3\32\4\0\1\33"+
    "\4\0\1\30\4\0\3\33\4\0\1\34\4\0\1\30"+
    "\4\0\3\34\3\0\1\25\1\14\1\35\1\36\2\0"+
    "\1\14\2\0\1\14\1\17\3\14\3\0\1\26\1\0"+
    "\1\26\6\0\1\26\15\0\1\37\13\0\1\40\11\0"+
    "\3\40\10\0\1\41\14\0\1\42\11\0\3\42\4\0"+
    "\1\43\4\0\1\37\4\0\3\43\4\0\1\44\4\0"+
    "\1\37\4\0\3\44\3\0\2\14\1\35\1\36\2\0"+
    "\1\14\2\0\1\14\1\17\3\14\3\0\1\45\3\14"+
    "\2\0\1\14\2\0\1\14\1\17\3\14\4\0\1\46"+
    "\11\0\3\46\4\0\1\47\11\0\3\47\11\0\1\50"+
    "\22\0\1\27\11\0\1\51\11\0\3\51\4\0\1\52"+
    "\11\0\3\52\3\0\1\53\1\14\1\54\1\14\2\0"+
    "\1\14\2\0\1\14\1\17\3\14\4\0\1\55\11\0"+
    "\3\55\11\0\1\56\13\0\1\57\11\0\3\57\4\0"+
    "\1\60\11\0\3\60\4\0\1\61\11\0\3\61\3\0"+
    "\1\53\1\14\1\62\1\14\2\0\1\14\2\0\1\14"+
    "\1\17\3\14\3\0\1\63\1\14\1\54\1\14\2\0"+
    "\1\14\2\0\1\14\1\17\3\14\11\0\1\64\13\0"+
    "\1\65\11\0\3\65\4\0\1\66\11\0\3\66\4\0"+
    "\1\67\11\0\3\67\4\0\1\70\11\0\3\70\3\0"+
    "\1\63\1\14\1\62\1\14\2\0\1\14\2\0\1\14"+
    "\1\17\3\14\3\0\1\63\1\14\1\71\1\14\2\0"+
    "\1\14\2\0\1\14\1\17\3\14\4\0\1\72\11\0"+
    "\3\72\4\0\1\73\11\0\3\73\11\0\1\74\13\0"+
    "\1\75\11\0\3\75\4\0\1\76\11\0\3\76\3\0"+
    "\2\14\1\71\1\14\2\0\1\14\2\0\1\14\1\17"+
    "\3\14\4\0\1\77\11\0\3\77\11\0\1\100\13\0"+
    "\1\101\11\0\3\101\4\0\1\102\11\0\3\102\4\0"+
    "\1\103\11\0\3\103\11\0\1\104\13\0\1\105\11\0"+
    "\3\105\4\0\1\106\11\0\3\106\4\0\1\107\11\0"+
    "\3\107\4\0\1\110\11\0\3\110\4\0\1\111\11\0"+
    "\3\111\4\0\1\112\11\0\3\112\11\0\1\113\13\0"+
    "\1\114\11\0\3\114\4\0\1\115\11\0\3\115\4\0"+
    "\1\116\11\0\3\116\11\0\1\117\13\0\1\120\11\0"+
    "\3\120\4\0\1\121\11\0\3\121\4\0\1\122\11\0"+
    "\3\122\11\0\1\123\13\0\1\124\11\0\3\124\4\0"+
    "\1\125\11\0\3\125\4\0\1\126\11\0\3\126\4\0"+
    "\1\127\11\0\3\127\4\0\1\130\11\0\3\130\4\0"+
    "\1\131\11\0\3\131\11\0\1\132\13\0\1\133\11\0"+
    "\3\133\4\0\1\134\11\0\3\134\4\0\1\135\11\0"+
    "\3\135\4\0\1\136\11\0\3\136\4\0\1\137\11\0"+
    "\3\137\4\0\1\140\11\0\3\140\4\0\1\141\11\0"+
    "\3\141\4\0\1\142\11\0\3\142\4\0\1\143\11\0"+
    "\3\143\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1564];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\13\0\1\1\24\0\1\1\6\0"+
    "\2\1\5\0\1\1\20\0\1\1\16\0\1\11\7\0"+
    "\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  NewLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  NewLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 78) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return ERROR;
          }
        case 9: break;
        case 2: 
          { /*Ignore*/
          }
        case 10: break;
        case 3: 
          { lexeme =yytext(); return Email;
          }
        case 11: break;
        case 4: 
          { lexeme =yytext(); return Nombre;
          }
        case 12: break;
        case 5: 
          { lexeme =yytext(); return Telefono;
          }
        case 13: break;
        case 6: 
          { lexeme =yytext(); return Celular;
          }
        case 14: break;
        case 7: 
          { lexeme =yytext(); return Mastercard;
          }
        case 15: break;
        case 8: 
          { lexeme =yytext(); return Visa;
          }
        case 16: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
